package naomod.fsm.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptFSM = createDescriptorForFSM();
  /*package*/ final ConceptDescriptor myConceptState = createDescriptorForState();
  /*package*/ final ConceptDescriptor myConceptStateReference = createDescriptorForStateReference();
  /*package*/ final ConceptDescriptor myConceptTransition = createDescriptorForTransition();
  /*package*/ final ConceptDescriptor myConceptTransitionReference = createDescriptorForTransitionReference();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptFSM, myConceptState, myConceptStateReference, myConceptTransition, myConceptTransitionReference);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.FSM:
        return myConceptFSM;
      case LanguageConceptSwitch.State:
        return myConceptState;
      case LanguageConceptSwitch.StateReference:
        return myConceptStateReference;
      case LanguageConceptSwitch.Transition:
        return myConceptTransition;
      case LanguageConceptSwitch.TransitionReference:
        return myConceptTransitionReference;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForFSM() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("naomod.fsm", "FSM", 0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0b98L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:50f59b2e-063d-4280-993f-f5f8a961fbdf(naomod.fsm.structure)/8475187935299898264");
    b.version(2);
    b.associate("initialState", 0x759dea86103a0bc4L).target(0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0b99L).optional(false).origin("8475187935299898308").done();
    b.aggregate("ownedStates", 0x759dea86103a0bbbL).target(0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0b99L).optional(true).ordered(true).multiple(true).origin("8475187935299898299").done();
    b.aggregate("finalStates", 0x759dea86103a0beeL).target(0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0be9L).optional(false).ordered(true).multiple(true).origin("8475187935299898350").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForState() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("naomod.fsm", "State", 0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0b99L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:50f59b2e-063d-4280-993f-f5f8a961fbdf(naomod.fsm.structure)/8475187935299898265");
    b.version(2);
    b.aggregate("outgoingTransitions", 0x759dea86103a0bcbL).target(0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0ba6L).optional(true).ordered(true).multiple(true).origin("8475187935299898315").done();
    b.aggregate("incomingTransitions", 0x759dea86103a0bd9L).target(0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0bd6L).optional(true).ordered(true).multiple(true).origin("8475187935299898329").done();
    b.alias("state");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStateReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("naomod.fsm", "StateReference", 0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0be9L);
    b.class_(false, false, false);
    b.origin("r:50f59b2e-063d-4280-993f-f5f8a961fbdf(naomod.fsm.structure)/8475187935299898345");
    b.version(2);
    b.associate("state", 0x759dea86103a0beaL).target(0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0b99L).optional(false).origin("8475187935299898346").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTransition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("naomod.fsm", "Transition", 0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0ba6L);
    b.class_(false, false, false);
    b.origin("r:50f59b2e-063d-4280-993f-f5f8a961fbdf(naomod.fsm.structure)/8475187935299898278");
    b.version(2);
    b.property("input", 0x759dea86103a0ba7L).type(PrimitiveTypeId.STRING).origin("8475187935299898279").done();
    b.property("output", 0x759dea86103a0badL).type(PrimitiveTypeId.STRING).origin("8475187935299898285").done();
    b.associate("target", 0x759dea86103a0bb2L).target(0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0b99L).optional(false).origin("8475187935299898290").done();
    b.alias("transition");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTransitionReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("naomod.fsm", "TransitionReference", 0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0bd6L);
    b.class_(false, false, false);
    b.origin("r:50f59b2e-063d-4280-993f-f5f8a961fbdf(naomod.fsm.structure)/8475187935299898326");
    b.version(2);
    b.associate("transition", 0x759dea86103a0bd7L).target(0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0ba6L).optional(false).origin("8475187935299898327").done();
    return b.create();
  }
}
