package naomod.fsm.behavior;

/*Generated by MPS */

import javax.swing.SwingUtilities;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.baseLanguage.closures.runtime.Wrappers;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import java.util.Objects;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class FSMInterpreter {

  private FSMContext context;

  public FSMInterpreter(FSMContext context) {
    this.context = context;
  }
  public void launchUI() {
    SwingUtilities.invokeLater(new UI(this, SPropertyOperations.getString(SNodeOperations.as(SNodeOperations.getContainingRoot(context.getCurrentState()), CONCEPTS.FSM$3f), PROPS.name$MnvL)));
  }

  public String computeStep(final String inputString) {

    if (inputString.equals("")) {
      if (checkFinalState()) {
        return "Execution succesful !";
      } else {
        return "Execution failed !";
      }
    }

    final Wrappers._T<String> outputString = new Wrappers._T<String>();

    SNodeOperations.getModel(context.getCurrentState()).getRepository().getModelAccess().runReadAction(new Runnable() {
      public void run() {
        SNode candidateTransition = State__BehaviorDescriptor.findOutgoingTransitionWithInput_id7mtUCoggcEB.invoke(context.getCurrentState(), inputString);

        if (!((candidateTransition == null))) {
          context.setCurrentState(SLinkOperations.getTarget(candidateTransition, LINKS.target$$6wD));
          outputString.value = SPropertyOperations.getString(candidateTransition, PROPS.output$$0qf);
        } else {
          outputString.value = "No transition with input " + inputString + " from the current state.\n Execution failed !";
        }
      }
    });

    return outputString.value;
  }

  private boolean checkFinalState() {
    final Wrappers._boolean isFinal = new Wrappers._boolean(false);

    SNodeOperations.getModel(context.getCurrentState()).getRepository().getModelAccess().runReadAction(new Runnable() {
      public void run() {
        ListSequence.fromList(SLinkOperations.getChildren(SNodeOperations.as(SNodeOperations.getParent(context.getCurrentState()), CONCEPTS.FSM$3f), LINKS.finalStates$BaBL)).visitAll(new IVisitor<SNode>() {
          public void visit(SNode it) {
            if (Objects.equals(SLinkOperations.getTarget(it, LINKS.state$Bb$k), context.getCurrentState())) {
              isFinal.value = true;
            }
          }
        });
      }
    });

    return isFinal.value;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept FSM$3f = MetaAdapterFactory.getConcept(0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0b98L, "naomod.fsm.structure.FSM");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty output$$0qf = MetaAdapterFactory.getProperty(0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0ba6L, 0x759dea86103a0badL, "output");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink target$$6wD = MetaAdapterFactory.getReferenceLink(0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0ba6L, 0x759dea86103a0bb2L, "target");
    /*package*/ static final SContainmentLink finalStates$BaBL = MetaAdapterFactory.getContainmentLink(0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0b98L, 0x759dea86103a0beeL, "finalStates");
    /*package*/ static final SReferenceLink state$Bb$k = MetaAdapterFactory.getReferenceLink(0xc3333435bd7f4f7cL, 0x9eabb88e0228cd0eL, 0x759dea86103a0be9L, 0x759dea86103a0beaL, "state");
  }
}
