package naomod.fsm.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class StepResult {
  private boolean isPossible;
  private String output;
  private SNode currentState;

  public StepResult(boolean isPossible) {
    this.isPossible = isPossible;
  }

  public StepResult(boolean isPossible, String output, SNode currentState) {
    this.isPossible = isPossible;
    this.output = output;
    this.currentState = currentState;
  }

  public boolean isPossible() {
    return this.isPossible;
  }
  public String getOutput() {
    return this.output;
  }
  public SNode getCurrentState() {
    return this.currentState;
  }
}
