package naomod.fsm.behavior;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.GridLayout;
import javax.swing.JLabel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class UI extends JFrame implements Runnable {

  private FSMInterpreter interpreter;
  private String fsmName;
  private JTextField inputField = new JTextField();
  private JTextField outputField = new JTextField();
  private JButton button = new JButton("Compute");

  public UI(FSMInterpreter interpreter, String fsmName) {
    this.interpreter = interpreter;
    this.fsmName = fsmName;
  }

  @Override
  public void run() {
    setTitle(fsmName);
    setLayout(new GridLayout(0, 2));
    add(new JLabel("Input"));
    add(inputField);
    add(new JLabel("Output"));
    outputField.setEditable(false);
    add(outputField);
    button.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent p1) {
        outputField.setText(interpreter.computeStep(inputField.getText()));
        inputField.setText("");
      }
    });
    add(button);

    setDefaultCloseOperation(EXIT_ON_CLOSE);
    pack();
    setVisible(true);
  }
}
